Tripur.html
BlackTimber-Labs/Portfolio-Website pull request #78
Opened 2021-10-04 13:45 UTC by tripur3121

2021-10-04 14:21 UTC, RITEKROUNAK commented on Tripur.html
> +            <h1 class="name">saksham somani</h1>
Nice Try.

2021-10-04 14:21 UTC, RITEKROUNAK commented on Tripur.html
> +                <strong> Made with 💖 by Tripur S Joshi. </strong>
Perfect 👍

2021-10-04 14:24 UTC, RITEKROUNAK requested changes
Atleast Edit Your Name.

2021-10-04 18:02 UTC, tripur3121 commented on Tripur.html
> +                ><strong> &lt;saksham /&gt; </strong></a
Done.

2021-10-05 05:54 UTC, RITEKROUNAK approved these changes

2021-10-05 05:55 UTC, merged